# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "activesupport", "= 6.1.4.4"

gem "minitest", "~> 5.15"

gem "rubocop", "= 0.86"

gem "steep", "~> 0.47.0"
